a = input("name of user: ")
print("my name is: ",a)
b=input("enter your village:")
print("vilage name is:",b)
c=input("your distric:")
print("my distric name is: ",c)
d=input("your state")
print("state is:",d)
print("your address is ",a+b+c+d)